#!/usr/bin/env node
/* ============================================================
   build.js — bakes the case studies into the HTML.

   Why this exists: js/site.js is the one place the project text
   lives, but content that only appears after JavaScript runs is
   invisible to search crawlers, link-preview bots, and applicant
   tracking systems. This script renders that data to static HTML
   and writes it into the marked blocks in index.html and
   projects/*.html, so the pages are complete on load.

   Run it after every edit to js/site.js:

       node build.js

   No dependencies, Node's built-ins only. Nothing outside the
   BUILD:*:start / BUILD:*:end markers is touched.
   ============================================================ */

"use strict";

const fs = require("fs");
const path = require("path");
const vm = require("vm");

const ROOT = __dirname;
const read = (p) => fs.readFileSync(path.join(ROOT, p), "utf8");

/* ---------- Load site.js + render.js the same way a browser would ----------
   Both are plain scripts that assume a `window`. Running them in one shared
   context lets us read their top-level `const`s afterwards, so the build and
   the browser render from identical code. */
const sandbox = { window: {}, console };
vm.createContext(sandbox);
vm.runInContext(read("js/site.js"), sandbox, { filename: "js/site.js" });
vm.runInContext(read("js/render.js"), sandbox, { filename: "js/render.js" });

const { SITE, PROJECTS } = vm.runInContext("({ SITE, PROJECTS })", sandbox);
const R = sandbox.window.PortfolioRender;

if (!R || !Array.isArray(PROJECTS)) {
  console.error("build: could not load site data. Is js/site.js valid?");
  process.exit(1);
}

/* ---------- Marker replacement ----------
   A block looks like:
     <!-- BUILD:name:start -->  ...generated...  <!-- BUILD:name:end -->
   Everything between the markers is replaced; the markers stay put. */
function replaceBlock(source, name, html, file) {
  const start = `<!-- BUILD:${name}:start -->`;
  const end = `<!-- BUILD:${name}:end -->`;
  const i = source.indexOf(start);
  const j = source.indexOf(end);
  if (i === -1 || j === -1) {
    throw new Error(`${file}: missing ${start} / ${end} markers`);
  }
  if (j < i) {
    throw new Error(`${file}: ${end} appears before ${start}`);
  }
  const generated =
    "\n<!-- Generated by build.js from js/site.js. Edit that file, not this block. -->\n" +
    html +
    "\n";
  return source.slice(0, i + start.length) + generated + source.slice(j);
}

function writeIfChanged(relPath, next) {
  const abs = path.join(ROOT, relPath);
  const prev = fs.readFileSync(abs, "utf8");
  if (prev === next) {
    console.log(`  unchanged  ${relPath}`);
    return false;
  }
  fs.writeFileSync(abs, next);
  console.log(`  written    ${relPath}`);
  return true;
}

/* ---------- 1. The project grid on the home page ---------- */
console.log("build: rendering case studies from js/site.js\n");

let index = read("index.html");
const cardsHTML = PROJECTS.map((p) =>
  R.projectCardHTML(p, { pagePrefix: "projects/" })
).join("\n");
index = replaceBlock(index, "project-grid", cardsHTML, "index.html");
writeIfChanged("index.html", index);

/* ---------- 2. Each standalone case-study page ---------- */
for (const p of PROJECTS) {
  const rel = path.join("projects", `${p.slug}.html`);
  if (!fs.existsSync(path.join(ROOT, rel))) {
    console.warn(`  MISSING    ${rel} (project "${p.slug}" has no page)`);
    continue;
  }
  const bodyHTML = R.caseStudyBodyHTML(p, {
    assetPrefix: "../",
    headingTag: "h2",
  });
  let page = read(rel);
  page = replaceBlock(page, "case-study", bodyHTML, rel);
  writeIfChanged(rel, page);
}

/* ---------- 3. Flag anything still waiting on Rebekah ---------- */
const pending = PROJECTS.filter((p) => p.repo && p.repo.url && !p.repo.published);
const noRepo = PROJECTS.filter((p) => !p.repo);

console.log("\nbuild: done.");
if (pending.length) {
  console.log("\n  Repos not published yet (button shows a placeholder):");
  for (const p of pending) console.log(`    - ${p.title}\n        ${p.repo.url}`);
  console.log("\n  Publish, then set published: true in js/site.js and rerun.");
}
if (noRepo.length) {
  console.log("\n  No public repo by design:");
  for (const p of noRepo) console.log(`    - ${p.title}`);
}
